apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job_name: job-1775147688776689-8d6cd71a-b421-4028-bf83-bb6ba33e03eb
  name: job-1775147688776689-8d6cd71a-b421-4028-bf83-bb6ba33e03eb
  namespace: job-namespace
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        pod_name: calrissian_pod
      name: calrissian_pod
    spec:
      containers:
        - args:
            - --stdout
            - /calrissian/output.json
            - --stderr
            - /calrissian/stderr.log
            - --usage-report
            - /calrissian/report.json
            - --max-ram
            - 4G
            - --max-cores
            - '2'
            - --tmp-outdir-prefix
            - /calrissian/
            - --outdir
            - /calrissian/
            - --pod-env-vars
            - /pod-env-vars/pod_env_vars.json
            - --debug
            - --enable-ext
            - /workflow-input/workflow.cwl
            - /workflow-params/params.yml
          command:
            - calrissian
          env:
            - name: CALRISSIAN_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CALRISSIAN_DELETE_PODS
              value: 'false'
          image: terradue/calrissian:0.12.0
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 30
          name: calrissian
          resources:
            limits:
              cpu: 2000m
              memory: 2G
            requests:
              cpu: 1000m
              memory: 1G
          volumeMounts:
            - mountPath: /workflow-input
              name: volume-cwl-workflow
            - mountPath: /workflow-params
              name: volume-params
            - mountPath: /calrissian
              name: volume-calrissian-wdir
              readOnly: false
            - mountPath: /pod-env-vars
              name: volume-pod-env-vars
      restartPolicy: Never
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
      terminationGracePeriodSeconds: 120
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: cwl-workflow
                mode: 420
                path: workflow.cwl
            name: cwl-workflow
            optional: false
          name: volume-cwl-workflow
        - configMap:
            defaultMode: 420
            items:
              - key: params
                mode: 420
                path: params.yml
            name: params
            optional: false
          name: volume-params
        - name: volume-calrissian-wdir
          persistentVolumeClaim:
            claimName: calrissian-wdir
            readOnly: false
        - configMap:
            defaultMode: 420
            items:
              - key: pod-env-vars
                mode: 420
                path: pod_env_vars.json
            name: pod-env-vars
            optional: false
          name: volume-pod-env-vars
